### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by pattacini** [robotology/visual-tracking-control#1]

**Comment by pattacini** [comment]
@claudiofantacci I believe you're orderly enough to take care of this 😉 

First things first, references can be updated with the new arXiv as well as by replacing the preprint with the pointer to the proceeding.

**Comment by claudiofantacci** [comment]
Will do.
I'm preparing the whole repo for a first (let's say) stable release.

I'll do a one pass update of everything once I'll merge devel into master.
